=== adinef/PKCK/Task3/movies.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://it.p.lodz.pl/pkck"
			xmlns:filmsSpace="http://it.p.lodz.pl/pkck/210171"
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://it.p.lodz.pl/pkck"
			elementFormDefault="qualified">
  <xs:element name="FilmDatabase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Head" />
        <xs:element ref="Categories" />
        <xs:element ref="Films" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Author">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="([a-żA-Ż ])*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="EMail">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:whiteSpace value="collapse"/>
        <xs:pattern value="([a-z0-9])*(@)([a-z .])*(.)(a-z)*" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Name">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="([a-żA-Ż .':])*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Head">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Author" />
        <xs:element ref="EMail" />
        <xs:element ref="Name" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LastName">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="([a-żA-Ż -.'])*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Categories">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Category" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Category">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="catRefId" type="xs:IDREF" use="optional" />
          <xs:attribute name="catId" type="xs:ID" use="optional" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Films">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Film" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Lead">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" />
        <xs:element ref="LastName" />
        <xs:element ref="BirthDate" />
      </xs:sequence>
      <xs:attribute name="leadId" type="xs:ID" />
      <xs:attribute name="leadRefId" type="xs:IDREF" />
    </xs:complexType>
  </xs:element>
  <xs:element name="BirthDate" type="xs:date" />
  <xs:element name="Director">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" />
        <xs:element ref="LastName" />
        <xs:element ref="BirthDate" />
      </xs:sequence>
      <xs:attribute name="directorId" type="xs:ID" />
      <xs:attribute name="directorRefId" type="xs:IDREF" />
    </xs:complexType>
  </xs:element>
  <xs:element name="Film">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name" />
        <xs:element ref="AvgScore" />
        <xs:element ref="Categories" />
        <xs:element ref="Description" />
        <xs:element ref="ReleaseYear" />
        <xs:element ref="Lead" />
        <xs:element ref="Director" />
      </xs:sequence>
      <xs:attribute name="filmId" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="AvgScore">
    <xs:simpleType>
      <xs:restriction base="xs:double">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="10"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="Description" type="xs:string" />
  <xs:element name="ReleaseYear" type="xs:integer" />
</xs:schema>

=== adinef/PKCK/Task5/movies.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<FilmDatabase xmlns="http://it.p.lodz.pl/pkck" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="C:\Users\Script\Desktop\PROJECTS\PKCK\Task5\movies.xsd">
    <Head>
        <Author>Adrian Fijałkowski</Author>
        <EMail>210171@edu.p.lodz.pl</EMail>
        <Name>Baza filmów</Name>
    </Head>
    <Categories>
        <Category id="CAT01">Horror</Category>
        <Category id="CAT02">Dramat</Category>
        <Category id="CAT03">Wojenny</Category>
        <Category id="CAT04">Akcja</Category>
        <Category id="CAT05">Sci-Fi</Category>
        <Category id="CAT06">Komedia</Category>
        <Category id="CAT07">Przygodowy</Category>
        <Category id="CAT08">Kryminalny</Category>
        <Category id="CAT09">Fantasy</Category>
    </Categories>
    <Actors>
        <Lead id="L01">
            <Name>Jack</Name>
            <LastName>Nicholson</LastName>
            <BirthDate>1937-04-22</BirthDate>
        </Lead>
        <Lead id="L02">
            <Name>Emile</Name>
            <LastName>Hirsch</LastName>
            <BirthDate>1985-03-13</BirthDate>
        </Lead>
        <Lead id="L03">
            <Name>Martin</Name>
            <LastName>Sheen</LastName>
            <BirthDate>1940-08-03</BirthDate>
        </Lead>
        <Lead id="L04">
            <Name>Brie</Name>
            <LastName>Larson</LastName>
            <BirthDate>1989-10-01</BirthDate>
        </Lead>
        <Lead id="L05">
            <Name>Tom</Name>
            <LastName>Hanks</LastName>
            <BirthDate>1956-07-09</BirthDate>
        </Lead>
        <Lead id="L06">
            <Name>Norman</Name>
            <LastName>Reedus</LastName>
            <BirthDate>1969-01-06</BirthDate>
        </Lead>
        <Lead id="L07">
            <Name>Marek</Name>
            <LastName>Kondrat</LastName>
            <BirthDate>1950-10-18</BirthDate>
        </Lead>
        <Lead id="L08">
            <Name>Bryan</Name>
            <LastName>Cranston</LastName>
            <BirthDate>1956-03-07</BirthDate>
        </Lead>
        <Lead id="L09">
            <Name>Daniel</Name>
            <LastName></LastName>
            <BirthDate>1957-04-29</BirthDate>
        </Lead>
        <Lead id="L10">
            <Name>Billy Cristal</Name>
            <LastName>Sheen</LastName>
            <BirthDate>1940-08-03</BirthDate>
        </Lead>
        <Lead id="L11">
            <Name>Meg</Name>
            <LastName>Ryan</LastName>
            <BirthDate>1961-11-19</BirthDate>
        </Lead>
        <Lead id="L12">
            <Name>Gerard</Name>
            <LastName>Butler</LastName>
            <BirthDate>1969-11-13</BirthDate>
        </Lead>
        <Lead id="L13">
            <Name>Hugh</Name>
            <LastName>Jackman</LastName>
            <BirthDate>1968-10-12</BirthDate>
        </Lead>
        <Lead id="L14">
            <Name>Brad</Name>
            <LastName>Pitt</LastName>
            <BirthDate>1963-12-18</BirthDate>
        </Lead>
        <Lead id="L15">
            <Name>Eddie</Name>
            <LastName>Redmayne</LastName>
            <BirthDate>1982-01-06</BirthDate>
        </Lead>
        <Lead id="L16">
            <Name>Andrzej</Name>
            <LastName>Chyra</LastName>
            <BirthDate>1964-08-27</BirthDate>
        </Lead>
        <Lead id="L17">
            <Name>Ryan</Name>
            <LastName>Gosling</LastName>
            <BirthDate>1980-11-12</BirthDate>
        </Lead>
    </Actors>
    <Directors>
        <Director id="D01">
            <Name>Stanley</Name>
            <LastName>Kubrick</LastName>
            <BirthDate>1928-07-26</BirthDate>
        </Director>
        <Director id="D02">
            <Name>Sean</Name>
            <LastName>Penn</LastName>
            <BirthDate>1960-08-17</BirthDate>
        </Director>
        <Director id="D03">
            <Name>Francis Ford</Name>
            <LastName>Copolla</LastName>
            <BirthDate>1939-04-07</BirthDate>
        </Director>
        <Director id="D04">
            <Name>Anna</Name>
            <LastName>Bond</LastName>
            <BirthDate>1990-02-02</BirthDate>
        </Director>
        <Director id="D05">
            <Name>Johnathan</Name>
            <LastName>Demme</LastName>
            <BirthDate>1944-02-22</BirthDate>
        </Director>
        <Director id="D06">
            <Name>Troy</Name>
            <LastName>Duffy</LastName>
            <BirthDate>1971-06-08</BirthDate>
        </Director>
        <Director id="D07">
            <Name>Marek</Name>
            <LastName>Koterski</LastName>
            <BirthDate>1942-06-03</BirthDate>
        </Director>
        <Director id="D08">
            <Name>Wes</Name>
            <LastName>Adnerson</LastName>
            <BirthDate>1969-05-01</BirthDate>
        </Director>
        <Director id="D09">
            <Name>Michael</Name>
            <LastName>Mann</LastName>
            <BirthDate>1943-02-05</BirthDate>
        </Director>
        <Director id="D10">
            <Name>James L.</Name>
            <LastName>Brooks</LastName>
            <BirthDate>1940-05-09</BirthDate>
        </Director>
        <Director id="D11">
            <Name>Milos</Name>
            <LastName>Forman</LastName>
            <BirthDate>1932-02-18</BirthDate>
        </Director>
        <Director id="D12">
            <Name>Rob</Name>
            <LastName>Reiner</LastName>
            <BirthDate>1945-03-06</BirthDate>
        </Director>
        <Director id="D13">
            <Name>Cheryl</Name>
            <LastName>Hines</LastName>
            <BirthDate>1965-09-29</BirthDate>
        </Director>
        <Director id="D14">
            <Name>Guy</Name>
            <LastName>Ritchie</LastName>
            <BirthDate>1968-10-10</BirthDate>
        </Director>
        <Director id="D15">
            <Name>Tom</Name>
            <LastName>Hooper</LastName>
            <BirthDate>1972-10-01</BirthDate>
        </Director>
        <Director id="D16">
            <Name>David</Name>
            <LastName>Yates</LastName>
            <BirthDate>1962-11-30</BirthDate>
        </Director>
        <Director id="D17">
            <Name>Feliks</Name>
            <LastName>Falk</LastName>
            <BirthDate>1941-02-25</BirthDate>
        </Director>
        <Director id="D18">
            <Name>Nicholas</Name>
            <LastName>Winding Refn</LastName>
            <BirthDate>1970-06-29</BirthDate>
        </Director>
    </Directors>
    <Films>
        <Film id="F01" leadId="L01" directorId="D01">
            <Name>Lśnienie</Name>
            <AvgScore>8.2</AvgScore>
            <Categories>
                <Category>CAT01</Category>
            </Categories>
            <Description>Jack podejmuje pracę stróża odciętego od świata hotelu Overlook.                Wkrótce idylla zamienia się w koszmar.</Description>
            <ReleaseYear>1980</ReleaseYear>
        </Film>
        <Film id="F02" leadId="L02" directorId="D02">
            <Name>Wszystko za życie</Name>
            <AvgScore>8.0</AvgScore>
            <Categories>
                <Category>CAT02</Category>
            </Categories>
            <Description>Christopher kończy studia, ale zamiast poświęcić się karierze zawodowej,                wyrusza autostopem w kierunku Alaski.</Description>
            <ReleaseYear>2007</ReleaseYear>
        </Film>
        <Film id="F03" leadId="L03" directorId="D03">
            <Name>Czas apokalipsy</Name>
            <AvgScore>8.5</AvgScore>
            <Categories>
                <Category>CAT02</Category>
                <Category>CAT03</Category>
            </Categories>
            <Description>Adaptacja opowiadania Josepha Conrada "Jądro ciemności".                Przeniesiona w realia wojny wietnamskiej historia kapitana Willarda,                który otrzymuje misję odnalezienia i zlikwidowania pułkownika Kurtza.</Description>
            <ReleaseYear>1979</ReleaseYear>
        </Film>
        <Film id="F04" leadId="L04" directorId="D04">
            <Name>Kapitan Marvel</Name>
            <AvgScore>7.2</AvgScore>
            <Categories>
                <Category>CAT04</Category>
                <Category>CAT05</Category>
            </Categories>
            <Description>Ziemska kobieta po kontakcie z obcą rasą Kree otrzymuje nadludzkie moce.</Description>
            <ReleaseYear>2019</ReleaseYear>
        </Film>
        <Film id="F05" leadId="L05" directorId="D05">
            <Name>Filadelfia</Name>
            <AvgScore>10.0</AvgScore>
            <Categories>
                <Category>CAT02</Category>
            </Categories>
            <Description>Chorujący na AIDS prawnik zostaje zwolniony z pracy. Walcząc o godność, podaje do sądu byłych pracodawców.</Description>
            <ReleaseYear>1993</ReleaseYear>
        </Film>
        <Film id="F06" leadId="L06" directorId="D06">
            <Name>Święci z Bostonu</Name>
            <AvgScore>7.5</AvgScore>
            <Categories>
                <Category>CAT04</Category>
            </Categories>
            <Description>Dwaj bracia podejmują walkę z bostońskimi złoczyńcami. Są przekonani, że sam Bóg powierzył im taką                misję.</Description>
            <ReleaseYear>1999</ReleaseYear>
        </Film>
        <Film id="F07" leadId="L07" directorId="D07">
            <Name>Dzień świra</Name>
            <AvgScore>8.1</AvgScore>
            <Categories>
                <Category>CAT02</Category>
                <Category>CAT06</Category>
            </Categories>
            <Description>Adaś Miauczyński, 49-letni rozwiedziony polonista, żyje w kręgu swoich natręctw, nie potrafiąc wyrwać                się z nudy i rutyny dnia codziennego.</Description>
            <ReleaseYear>2002</ReleaseYear>
        </Film>
        <Film id="F08" leadId="L08" directorId="D08">
            <Name>Wyspa psów</Name>
